# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-25 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_uploadmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='add_count',
            field=models.IntegerField(default='0'),
        ),
    ]
