# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-25 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_uploadmodel_add_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(default='pending', max_length=200)),
                ('accessone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.RegisterModel')),
                ('accesstwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UploadModel')),
            ],
        ),
    ]
