# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-25 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_requestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='cate',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
